version: '3'

volumes:
  pgdata:

services:
  eduzenbot:
    build: .
    command: ["python3", "eduzen_bot", "-v", "--log_level=INFO"]
    volumes:
      - .:/code
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER

  # wdb:
  #   image: kozea/wdb
  #   ports:
  #     - "1984:1984"
