version: '3.8'

volumes:
  pgdata:
  shell_history:

services:
  eduzenbot:
    build:
      context: .
      target: dev
    command: ["sh", "/code/eduzen_bot/scripts/runserver.sh"]
    volumes:
      - .:/code
      - shell_history:/root/hist
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

  # wdb:
  #   image: kozea/wdb
  #   ports:
  #     - "1984:1984"
  # adminer:
  #   image: adminer:latest
  #   restart: always
  #   ports:
  #       - 8001:8080
