version: '3'

services:
  eduzenbot:
    build: .
    command: ["python3", "eduzen_bot", "-v"]
    volumes:
      - .:/code
    env_file:
      - .env

  # wdb:
  #   image: kozea/wdb
  #   ports:
  #     - "1984:1984"
