version: '3.9'

volumes:
  pgdata:
  shell_history:

services:

  eduzenbot:
    tty: true
    image: eduzen/bot:latest
    build:
      context: .
      target: dev
      cache_from:
        - eduzen/bot:latest
    # entrypoint: ["python",  "-m", "eduzenbot"]
    volumes:
      - .:/code
      - shell_history:/root/hist
    env_file:
      - .env
    links:
      - db

  db:
    image: postgres:13.4-alpine3.14
    command: ["postgres", "-c", "log_statement=none"]
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  wdb:
    profiles: ["dev"]
    image: kozea/wdb:3.3.0
    ports:
      - "1984:1984"

  adminer:
    profiles: ["dev"]
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8001:8080
