version: '3.8'

volumes:
  pgdata:
  shell_history:

services:

  eduzenbot:
    tty: true
    build:
      context: .
      target: dev

    # entrypoint: ["sh", "/code/eduzen_bot/scripts/runserver.sh"]
    entrypoint: ["python",  "-m", "eduzen_bot"]
    volumes:
      - .:/code
      - shell_history:/root/hist
    env_file:
      - .env
    links:
      - db
    environment:
      WDB_SOCKET_SERVER: wdb
      WDB_NO_BROWSER_AUTO_OPEN: "True"

  db:
    image: postgres:13-alpine
    command: ["postgres", "-c", "log_statement=none"]
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

  wdb:
    profiles: ["dev"]
    image: kozea/wdb
    ports:
      - "1984:1984"

  adminer:
    profiles: ["dev"]
    image: adminer:latest
    restart: always
    ports:
      - 8001:8080
