volumes:
  shell_history:

services:
  eduzenbot:
    tty: true
    image: eduzen/bot:latest
    build:
      context: .
      target: ${TARGET:-dev}
      cache_from:
        - eduzen/bot:latest
    develop:
      watch:
        - action: sync
          path: .
          target: /code
          ignore:
            - .venv/
            - .git/
            - .vscode/
            - .pytest_cache/
            - __pycache__/
        - action: rebuild
          path: ./pyproject.toml
    volumes:
      - /code/.venv
      - .:/code
      - shell_history:/root/hist
    env_file:
      - .env
