volumes:
  shell_history:
  pgdata:

services:
  eduzenbot:
    tty: true
    image: eduzen/bot:latest
    build:
      context: .
      target: ${TARGET:-dev}
      cache_from:
        - eduzen/bot:latest
    develop:
      watch:
        - action: sync
          path: .
          target: /code
          ignore:
            - .venv/
            - .git/
            - .vscode/
            - .pytest_cache/
            - __pycache__/
        - action: rebuild
          path: ./pyproject.toml
    volumes:
      - /code/.venv
      - .:/code
      - shell_history:/root/hist
    env_file:
      - .env

  db:
    image: postgres:17-alpine
    command: ["postgres", "-c", "log_statement=none"]
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  wdb:
    profiles: ["dev"]
    image: kozea/wdb:3.3.0
    ports:
      - "1984:1984"

  adminer:
    profiles: ["dev"]
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8001:8080
