[tool.poetry]
name = "bot"
version = "0.1.0"
description = ""
authors = ["Eduardo Enriquez (eduzen) <eduardo.a.enriquez@gmail.com>"]

[tool.black]
line-length = 120
safe = true
target-version = ['py38']

[tool.isort]
profile = "black"
include_trailing_comma = true

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^0.15.0"
python-telegram-bot = "^13.0"
sentry-sdk = "^0.19.1"
requests = "^2.25.1"
beautifulsoup4 = "^4.9.3"
docopt = "^0.6.2"
structlog = "^20.1.0"
tweepy = "^3.9.0"
tmdbsimple = "^2.6.6"
attrs = "^20.3.0"
emoji = "1.1.0"
peewee = "3.1.2"
nltk = "^3.5"
textblob = "^0.15.3"
regex = "^2020.11.13"
PyYAML = "^5.4.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
pytest = "^6.2.1"
ipython = "^7.19.0"
pre-commit = "^2.9.3"
wdb = "^3.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
