[tool.poetry]
name = "bot"
version = "0.1.0"
description = ""
authors = ["Eduardo Enriquez (eduzen) <eduardo.a.enriquez@gmail.com>"]

[tool.black]
line-length = 120
safe = true
target-version = ['py38']

[tool.isort]
profile = "black"
include_trailing_comma = true

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^0.15.0"
python-telegram-bot = "^13.2"
sentry-sdk = "^0.19.1"
requests = "^2.25.1"
beautifulsoup4 = "^4.9.3"
structlog = "^20.1.0"
tweepy = "^3.10.0"
tmdbsimple = "^2.6.6"
attrs = "^20.3.0"
emoji = "1.2.0"
peewee = "3.14.0"
nltk = "^3.5"
textblob = "^0.15.3"
regex = "^2020.11.13"
PyYAML = "^5.4.1"
ipdb = "^0.13.4"
psycopg2-binary = "^2.8.6"
yfinance = "^0.1.55"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
pytest = "^6.2.1"
ipython = "^7.19.0"
jedi = "0.18.0"
pre-commit = "^2.10.1"
wdb = "^3.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
create = true
# local = true
# in-project = true
