[tool.poetry]
name = "bot"
version = "0.1.0"
description = ""
authors = ["Eduardo Enriquez (eduzen) <eduardo.a.enriquez@gmail.com>"]

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "poetry-core>=1.0.0",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
safe = true
target-version = ['py38']
exclude = '''
(
  /(
    \.git
    | \.mypy_cache
    | \.pytest_cache
    | htmlcov
    | venv
    | .venv
  )/
)
'''

[tool.isort]
profile = "black"
include_trailing_comma = true

[tool.pytest.ini_options]
addopts = "-s"

[tool.poetry.dependencies]
attrs = "^21.2.0"
beautifulsoup4 = "^4.10.0"
colorama = "^0.4.4"
emoji = "1.4.2"
ipdb = "^0.13.4"
nltk = "^3.5"
textblob = "^0.15.3"
peewee = "3.14.4"
python = "^3.8"
python-telegram-bot = "13.11"
PyYAML = "^5.4.1"
psycopg2-binary = "^2.9.3"
regex = "^2021.8.21"
requests = "^2.26.0"
rich = "^10.16.2"
sentry-sdk = "^1.5.4"
tweepy = "^3.10.0"
tmdbsimple = "^2.9.1"
yfinance = "^0.1.70"
pendulum = "^2.1.2"
astral = "^2.2"
pytz = "^2021.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
factory-boy = "^3.2.1"
ipython = "^7.26"
jedi = "0.18.0"
pre-commit = "^2.14.1"
wdb = "^3.3.0"
ipdb = "^0.13.9"
Faker = "^8.12.0"
mypy = "^0.910"
types-requests = "^2.25.6"
pytest-vcr = "^1.0.2"



[virtualenvs]
create = false
# local = true
# in-project = true
