[tool.poetry]
name = "bot"
version = "0.1.0"
description = ""
authors = ["Eduardo Enriquez (eduzen) <eduardo.a.enriquez@gmail.com>"]

[tool.black]
line-length = 120
safe = true
target-version = ['py38']
exclude = '''
(
  /(
    \.git
    | \.mypy_cache
    | \.pytest_cache
    | htmlcov
    | venv
    | .venv
  )/
)
'''

[tool.isort]
profile = "black"
include_trailing_comma = true

[tool.pytest.ini_options]
addopts = "-s"
testpaths = ["tests"]

[tool.poetry.dependencies]
attrs = "^21.2.0"
beautifulsoup4 = "^4.9.3"
colorama = "^0.4.4"
emoji = "1.4.1"
ipdb = "^0.13.4"
nltk = "^3.5"
textblob = "^0.15.3"
peewee = "3.14.4"
python = "^3.8"
python-telegram-bot = "13.5"
PyYAML = "^5.4.1"
psycopg2-binary = "^2.9.1"
regex = "^2021.4.4"
requests = "^2.26.0"
rich = "^10.6.0"
sentry-sdk = "^1.3.1"
tweepy = "^3.10.0"
tmdbsimple = "^2.6.6"
yfinance = "^0.1.63"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
factory-boy = "^3.2.0"
ipython = "^7.25"
jedi = "0.18.0"
pre-commit = "^2.13.0"
wdb = "^3.3.0"
ipdb = "^0.13.9"
Faker = "^8.10.2"
mypy = "^0.910"
types-requests = "^2.25.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
create = false
# local = true
# in-project = true
