name: Docker

on:
  push:
    branches: [master, main]
    tags:
      - v*

env:
  IMAGE_NAME: eduzenbot

jobs:
  # See also https://docs.docker.com/docker-hub/builds/
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.15.0
        with:
          push: true
          tags: eduzen/bot:latest
          file: ./Dockerfile
          target: production

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
