name: lint

on: [push, pull_request, tags]

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.7]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9

    - name: Setup System
      run: |
        sudo apt-get install libsqlite3-dev

    - name: Cache dependency # caching dependency will make our build faster.
      uses: actions/cache@v2.1.6 # for more info checkout pip section documentation at https://github.com/actions/cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Run image
      uses: abatilo/actions-poetry@v2.1.2
      with:
        poetry-version: ${{ matrix.poetry-version }}
